config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :accounts
  resources :payments
  resources :plan_statuses
  resources :publisher_accounts
  resources :subscriber_payments
  resources :publisher_payments
  resources :payment_statuses
  resources :subscriptions
  resources :plans
  resources :subscribers
  resources :publishers
  resources :commission_masters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
  get "/home/index" => "home#index"
  get "/home/create_plan" => "home#create_plan"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    %w[publisher_id subscriber_id start_date end_date plan_id id created_at updated_at]
  end
  belongs_to :publisher
  belongs_to :subscriber
  belongs_to :plan
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  include Pundit
  include Pagy::Backend

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :set_subscription, only: %i[show edit update destroy]

  # GET /subscriptions
  def index
    authorize Subscription
    @subscriptions = Subscription
      .eager_load(:publisher)
      .eager_load(:subscriber)
      .eager_load(:plan)
    @q = @subscriptions.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @subscriptions = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /subscriptions/1
  def show
    authorize Subscription
  end

  # GET /subscriptions/new
  def new
    authorize Subscription
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
    authorize Subscription
  end

  # POST /subscriptions
  def create
    authorize Subscription
    @subscription = Subscription.new(subscription_params)

    if @subscription.save
      # TODO: ちゃんとリクエスト画面がわかるパラメーターを追加する
      if params[:commit] == "作成"
        redirect_to @subscription, notice: t("controller.create.success", model: Subscription.model_name.human)
      else
        redirect_to publisher_account_path(:id => params[:subscription][:publisher_id]), notice: t("controller.create.success", model: Subscription.model_name.human)
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /subscriptions/1
  def update
    authorize Subscription
    if @subscription.update(subscription_params)
      # TODO: ちゃんとリクエスト画面がわかるパラメーターを追加する
      if params[:commit] == "更新"
        redirect_to @subscription, notice: t("controller.edit.success", model: Subscription.model_name.human)
      else
        redirect_to home_create_plan_path, notice: t("controller.edit.success", model: Subscription.model_name.human)
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /subscriptions/1
  def destroy
    authorize Subscription
    @subscription.destroy!
    redirect_to subscriptions_url, notice: t("controller.destroy.success", model: Subscription.model_name.human)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription
        .eager_load(:publisher)
        .eager_load(:subscriber)
        .eager_load(:account)
        .eager_load(:plan)
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:publisher_id, :subscriber_id, :start_date, :end_date, :plan_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  include Pagy::Frontend
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if subscription.errors.any? -%>
  <div style="color: red">
    <h2><%= t("errors.template.header", model: Subscription.model_name.human, count: subscription.errors.count) %></h2>

    <ul>
    <% subscription.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <%- if subscription.persisted? -%>
  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.label Subscription.reflect_on_association(:publisher).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            Subscription.reflect_on_association(:publisher).foreign_key,
            Subscription.reflect_on_association(:publisher).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" },
            { id: "publisher-selector" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label Subscription.reflect_on_association(:subscriber).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            Subscription.reflect_on_association(:subscriber).foreign_key,
            Subscription.reflect_on_association(:publisher).klass.all.map {|e| [e.id, e.account.name]},
            :first,
            :last,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label :start_date, style: "display: block" %>
    <div class="ps-2">
      <%= form.date_field :start_date, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label :end_date, style: "display: block" %>
    <div class="ps-2">
      <%= form.date_field :end_date, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label Subscription.reflect_on_association(:plan).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            Subscription.reflect_on_association(:plan).foreign_key,
            Subscription.reflect_on_association(:plan).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" },
            { id: "plan-selector" }
          ) %>
    </div>
  </div>
  <%- if subscription.persisted? -%>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <table class="table table-hover">
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= subscription.id %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Subscription.human_attribute_name(:publisher_id) %>
        </strong>
      </td>
      <td>
        <%= subscription.publisher.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Subscription.human_attribute_name(:subscriber_id) %>
        </strong>
      </td>
      <td>
        <%= subscription.subscriber.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Subscription.human_attribute_name(:start_date) %>
        </strong>
      </td>
      <td>
        <%= subscription.start_date && l(subscription.start_date) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Subscription.human_attribute_name(:end_date) %>
        </strong>
      </td>
      <td>
        <%= subscription.end_date && l(subscription.end_date) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Subscription.human_attribute_name(:plan_id) %>
        </strong>
      </td>
      <td>
        <%= subscription.plan.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Subscription.human_attribute_name(:created_at) %>
        </strong>
      </td>
      <td>
        <%= subscription.created_at && l(subscription.created_at) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Subscription.human_attribute_name(:updated_at) %>
        </strong>
      </td>
      <td>
        <%= subscription.updated_at && l(subscription.updated_at) %>
      </td>
    </tr>
  </table>
</div>

app/views/subscriptions/edit.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "subscriptions/new" %>
<% end %>

<h1><%= t("view.edit.title", model: Subscription.model_name.human) %></h1>
<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: Subscription.model_name.human), @subscription %> |
  <%= link_to t("view.edit.move_to_index", model: Subscription.model_name.human.pluralize), subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "subscriptions/new" %>
<% end %>


<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">
    <p style="color: green"><%= notice %></p>

    <h1><%= Subscription.model_name.human %><%= link_to "", new_subscription_path, class: %w[bi bi-plus-circle-fill ms-2] %></h1>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label Subscription.reflect_on_association(:publisher).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  Subscription.reflect_on_association(:publisher).foreign_key + "_in".to_s,
                  Subscription.reflect_on_association(:publisher).klass.all.map {|e| [e.id, e.account.name]},
                  :first,
                  :last,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label Subscription.reflect_on_association(:subscriber).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  Subscription.reflect_on_association(:subscriber).foreign_key + "_in".to_s,
                  Subscription.reflect_on_association(:subscriber).klass.all.map {|e| [e.id, e.account.name]},
                  :first,
                  :last,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :start_date %>
          <div class="ps-2">
            <%= f.date_field :start_date_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.date_field :start_date_lteq_end_of_day, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :end_date %>
          <div class="ps-2">
            <%= f.date_field :end_date_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.date_field :end_date_lteq_end_of_day, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label Subscription.reflect_on_association(:plan).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  Subscription.reflect_on_association(:plan).foreign_key + "_in".to_s,
                  Subscription.reflect_on_association(:plan).klass.all,
                  :id,
                  :name,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :limit, id: "f-limit", value: params[:limit] || Pagy::DEFAULT[:limit] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="subscriptions" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :publisher_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :subscriber_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :start_date, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :end_date, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :plan_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody>
  <%- @subscriptions.each do |subscription| %>
        <tr
          tabindex="0"
          role="button"
          onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, subscription).to_s %>')"
          onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, subscription).to_s %>')">
          <td><%= subscription.id %></td>
          <td><%= subscription.publisher.account.name %></td>
          <td><%= subscription.subscriber.account.name %></td>
          <td><%= subscription.start_date && l(subscription.start_date) %></td>
          <td><%= subscription.end_date && l(subscription.end_date) %></td>
          <td><%= subscription.plan.name %></td>
          <td><%= subscription.created_at && l(subscription.created_at) %></td>
          <td><%= subscription.updated_at && l(subscription.updated_at) %></td>
          <td>
            <%= button_to(
                  t("helpers.submit.delete"),
                  subscription,
                  method: :delete,
                  tabindex: 0,
                  class: %w[btn btn-primary],
                  onclick: "handleDeleteListItem(arguments[0], this)",
                  data: { turbo_confirm: t("helpers.dialog.delete", id: subscription.id) }
                ) %>
          </td>
        </tr>
  <%- end %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_limit_selector_js(@pagy, item_name: "Subscription".pluralize(@pagy.count), id: "pagy-limit-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: Subscription.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

app/views/subscriptions/new.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "subscriptions/new" %>
<% end %>

<h1><%= t("view.new.title", model: Subscription.model_name.human) %></h1>
<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: Subscription.model_name.human.pluralize), subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "subscriptions/new" %>
<% end %>

<p style="color: green"><%= notice %></p>

<h1><%= Subscription.model_name.human %></h1>

<%= render @subscription %>

<div>
  <%= link_to t("view.show.move_to_update", model: Subscription.model_name.human), edit_subscription_path(@subscription) %> |
  <%= link_to t("view.show.move_to_index", model: Subscription.model_name.human.pluralize), subscriptions_path %>

  <%= button_to t("helpers.submit.delete"),
                @subscription,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @subscription.id) } %>
</div>