config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :accounts
  resources :payments
  resources :plan_statuses
  resources :publisher_accounts
  resources :subscriber_payments
  resources :publisher_payments
  resources :payment_statuses
  resources :subscriptions
  resources :plans
  resources :subscribers
  resources :publishers
  resources :commission_masters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
  get "/home/index" => "home#index"
  get "/home/create_plan" => "home#create_plan"
end

app/models/plan.rb
class Plan < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    %w[publisher_id name cost id created_at updated_at]
  end

  validates :publisher, uniqueness: { scope: :name }

  belongs_to :publisher
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  include Pundit
  include Pagy::Backend

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :set_plan, only: %i[show edit update destroy]

  # GET /plans
  def index
    authorize Plan
    @plans = Plan
      .eager_load(:publisher)
    @q = @plans.ransack(params[:q])
    @q.sorts = "id asc" if @q.sorts.empty?
    @pagy, @plans = pagy(@q.result, page: params[:page], items: params[:items])
  end

  # GET /plans/1
  def show
    authorize Plan
  end

  # GET /plans/new
  def new
    authorize Plan
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
    authorize Plan
  end

  # POST /plans
  def create
    authorize Plan
    @plan = Plan.new(plan_params)

    if @plan.save
      # TODO: ちゃんとリクエスト画面がわかるパラメーターを追加する
      if params[:commit] == "作成"
        redirect_to @plan, notice: t("controller.create.success", model: Plan.model_name.human)
      else
        redirect_to root_path, notice: t("controller.edit.success", model: Plan.model_name.human)
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /plans/1
  def update
    authorize Plan
    if @plan.update(plan_params)
      redirect_to @plan, notice: t("controller.edit.success", model: Plan.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /plans/1
  def destroy
    authorize Plan
    @plan.destroy!
    redirect_to plans_url, notice: t("controller.destroy.success", model: Plan.model_name.human)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan
        .eager_load(:publisher)
        .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:publisher_id, :name, :cost)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
  include Pagy::Frontend
end

app/views/plans/_form.html.erb
<%= form_with(model: plan, html: { class: %w[form-control form-control-sm] }) do |form| -%>
  <%- if plan.errors.any? -%>
  <div style="color: red">
    <h2><%= t("errors.template.header", model: Plan.model_name.human, count: plan.errors.count) %></h2>

    <ul>
    <% plan.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <%- if plan.persisted? -%>
  <div>
    <%= form.label :id, style: "display: block" %>
    <div class="ps-2">
      <%= form.number_field :id, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.label Plan.reflect_on_association(:publisher).foreign_key %>
    <div class="ps-2">
      <%= form.collection_select(
            Plan.reflect_on_association(:publisher).foreign_key,
            Plan.reflect_on_association(:publisher).klass.all,
            :id,
            :name,
            { include_blank: "選択なし" }
          ) %>
    </div>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_field :name, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <div>
    <%= form.label :cost, style: "display: block" %>
    <div class="ps-2">
      <%= form.text_field :cost, class: %w[form-control form-control-sm] %>
    </div>
  </div>
  <%- if plan.persisted? -%>
  <div>
    <%= form.label :created_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :created_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <div>
    <%= form.label :updated_at, style: "display: block" %>
    <div class="ps-2">
      <%= form.datetime_field :updated_at, class: %w[form-control form-control-sm], disabled: true %>
    </div>
  </div>
  <%- end -%>
  <div>
    <%= form.submit class: %w[btn btn-primary] %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div id="<%= dom_id plan %>">
  <table class="table table-hover">
    <tr>
      <td>
        <strong>Id:</strong>
      </td>
      <td>
        <%= plan.id %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Plan.human_attribute_name(:publisher_id) %>
        </strong>
      </td>
      <td>
        <%= plan.publisher.account.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Plan.human_attribute_name(:name) %>
        </strong>
      </td>
      <td>
        <%= plan.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Plan.human_attribute_name(:cost) %>
        </strong>
      </td>
      <td>
        <%= plan.cost %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Plan.human_attribute_name(:created_at) %>
        </strong>
      </td>
      <td>
        <%= plan.created_at && l(plan.created_at) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>
          <%= Plan.human_attribute_name(:updated_at) %>
        </strong>
      </td>
      <td>
        <%= plan.updated_at && l(plan.updated_at) %>
      </td>
    </tr>
  </table>
</div>

app/views/plans/edit.html.erb
<h1><%= t("view.edit.title", model: Plan.model_name.human) %></h1>
<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to t("view.edit.move_to_show", model: Plan.model_name.human), @plan %> |
  <%= link_to t("view.edit.move_to_index", model: Plan.model_name.human.pluralize), plans_path %>
</div>

app/views/plans/index.html.erb
<div style="display: flex;flex-direction: column;height: 100vh;">

  <header class="main-content-header">
    <p style="color: green"><%= notice %></p>

    <h1><%= Plan.model_name.human %><%= link_to "", new_plan_path, class: %w[bi bi-plus-circle-fill ms-2] %></h1>

  <div class="accordion">
    <div class="accordion-item">
      <h2 class="accordion-header" id="search-form-header">
        <button
          class="accordion-button collapsed"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#search-form"
          aria-expanded="false"
          aria-controls="search-form"><%= t("view.index.search_condition") %></button>
      </h2>
      <div id="search-form" class="panel panel-default accordion-collapse collapse" aria-labelledby="headingOne">
<%= search_form_for @q, html: { class: %w[form-control form-control-sm], data: { turbo_frame: "list" } } do |f| %>
        <div>
          <%= f.label :id_eq %>
          <div class="ps-2">
            <%= f.number_field :id_eq, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label Plan.reflect_on_association(:publisher).foreign_key + "_in".to_s %>
          <div class="ps-2">
            <%= f.collection_select(
                  Plan.reflect_on_association(:publisher).foreign_key + "_in".to_s,
                  Plan.reflect_on_association(:publisher).klass.all.map {|e| [e.id, e.account.name]},
                  :first,
                  :last,
                  {},
                  { multiple: true }
                ) %>
          </div>
        </div>
        <div>
          <%= f.label :name_cont %>
          <div class="ps-2">
            <%= f.search_field :name_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :cost_cont %>
          <div class="ps-2">
            <%= f.search_field :cost_cont, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :created_at %>
          <div class="ps-2">
            <%= f.datetime_field :created_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :created_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <div>
          <%= f.label :updated_at %>
          <div class="ps-2">
            <%= f.datetime_field :updated_at_gteq, class: %w[form-control form-control-sm] %>
            ～
            <%= f.datetime_field :updated_at_lteq_end_of_minute, class: %w[form-control form-control-sm] %>
          </div>
        </div>
        <%= f.hidden_field :limit, id: "f-limit", value: params[:limit] || Pagy::DEFAULT[:limit] %>
        <%= f.submit class: %w[btn btn-primary] %>
        <input
          type="reset"
          class="btn btn-primary"
          onclick="clear_form(arguments[0], this)"
          value="<%= t("helpers.submit.clear") %>">
<%- end -%>
      </div>
    </div>
  </header>

  <main style="flex-grow: 1;flex-shrink: 1;overflow-y: auto;">
<%= turbo_frame_tag "list" do %>
  <div id="plans" class="text-nowrap">
    <table class="table table-hover text-nowrap">
      <thead class="table-light sticky-top">
        <th><%= sort_link(@q, :id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :publisher_id, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :name, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :cost, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :created_at, default_order: :asc, class: "d-block") %></th>
        <th><%= sort_link(@q, :updated_at, default_order: :asc, class: "d-block") %></th>
        <th><%= t("view.index.operation") %></th>
      </thead>
      <tbody>
  <%- @plans.each do |plan| %>
        <tr
          tabindex="0"
          role="button"
          onkeypress="handleEnterKeypressListIten(arguments[0], this, '<%= url_target(nil, plan).to_s %>')"
          onclick="handleClickListItem(arguments[0], this, '<%= url_target(nil, plan).to_s %>')">
          <td><%= plan.id %></td>
          <td><%= plan.publisher.account.name %></td>
          <td><%= plan.name %></td>
          <td><%= plan.cost %></td>
          <td><%= plan.created_at && l(plan.created_at) %></td>
          <td><%= plan.updated_at && l(plan.updated_at) %></td>
          <td>
            <%= button_to(
                  t("helpers.submit.delete"),
                  plan,
                  method: :delete,
                  tabindex: 0,
                  class: %w[btn btn-primary],
                  onclick: "handleDeleteListItem(arguments[0], this)",
                  data: { turbo_confirm: t("helpers.dialog.delete", id: plan.id) }
                ) %>
          </td>
        </tr>
  <%- end %>
      </tbody>
    </table>
  </div>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_limit_selector_js(@pagy, item_name: "Plan".pluralize(@pagy.count), id: "pagy-limit-selector") %>
    <%= link_to(
          t("view.index.update_item_per_page", model: Plan.model_name.human),
          "javascript:void(0);",
          onClick: "updateItemPerPage(arguments[0],
          this)"
        ) %>
  </div>
<% end %>
  </main>
</div>

app/views/plans/new.html.erb
<h1><%= t("view.new.title", model: Plan.model_name.human) %></h1>
<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to t("view.new.move_to_index", model: Plan.model_name.human.pluralize), plans_path %>
</div>

app/views/plans/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= Plan.model_name.human %></h1>

<%= render @plan %>

<div>
  <%= link_to t("view.show.move_to_update", model: Plan.model_name.human), edit_plan_path(@plan) %> |
  <%= link_to t("view.show.move_to_index", model: Plan.model_name.human.pluralize), plans_path %>

  <%= button_to t("helpers.submit.delete"),
                @plan,
                method: :delete,
                class: %w[btn btn-primary],
                data: { turbo_confirm: t("helpers.dialog.delete", id: @plan.id) } %>
</div>