config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :accounts
  resources :payments
  resources :plan_statuses
  resources :publisher_accounts
  resources :subscriber_payments
  resources :publisher_payments
  resources :payment_statuses
  resources :subscriptions
  resources :plans
  resources :subscribers
  resources :publishers
  resources :commission_masters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
  get "/home/index" => "home#index"
  get "/home/create_plan" => "home#create_plan"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Subscription Management System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:js) %>
  </head>

  <body>
    <div class="flex-row-reverse" style="display: flex;">
      <div>
        <% if current_account then %><%= link_to current_account.name, edit_account_registration_path(current_account), class: "user-name" %>
          <p>
          publisher_id: <%= current_account.publisher_id %>, 
          subscriber_id: <%= current_account.subscriber_id %>
          </p>
        <% end %>
      </div>
    </div>
    <% if notice then %><p class="notice"><%= notice %></p><% end %>
    <% if alert then %><p class="alert"><%= alert %></p><% end %>
    <%= yield %>
    <ul>
      <li><%= link_to "マイページ", "/" %></li>
      <li><%= link_to "マイプランページ", home_create_plan_path() %></li>
      <li><%= link_to "パブリッシャーを探す", publisher_accounts_path %></li>
      <li><%= link_to "ログアウト", destroy_account_session_path, data: { turbo_method: :delete } %></li>
    </ul>
    <% if current_account && current_account.role == "admin" %>
    <div>
      <h1>管理画面</h1>
      <ul>
        <li><%= link_to :accounts, accounts_path %></li>
        <li><%= link_to :plans, plans_path %></li>
        <li><%= link_to :subscriptions, subscriptions_path %></li>
        <li><%= link_to :publishers, publishers_path %></li>
        <li><%= link_to :subscribers, subscribers_path %></li>
        <li><%= link_to :payments, payments_path %></li>
        <li><%= link_to :payment_statuses, payment_statuses_path %></li>
        <li><%= link_to :commission_masters, commission_masters_path %></li>
      </ul>
    </div>
    <% end %>
  </body>
</html>